Fixed Python 3.13 compatibility regarding urllib.parse module
